src/Entity/Chart.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="charts")
 */
class Chart
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $title;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $type;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $labels;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ChartData", mappedBy="chart")
     */
    protected $chartsData;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $data;

    public function __construct()
    {
        $this->chartsData = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getData(): ?string
    {
        return $this->data;
    }

    public function setData(?string $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getLabels(): ?string
    {
        return $this->labels;
    }

    public function setLabels(?string $labels): self
    {
        $this->labels = $labels;

        return $this;
    }

    /**
     * @return Collection|ChartData[]
     */
    public function getChartsData(): Collection
    {
        return $this->chartsData;
    }

    public function addChartsData(ChartData $chartsData): self
    {
        if (!$this->chartsData->contains($chartsData)) {
            $this->chartsData[] = $chartsData;
            $chartsData->setChart($this);
        }

        return $this;
    }

    public function removeChartsData(ChartData $chartsData): self
    {
        if ($this->chartsData->contains($chartsData)) {
            $this->chartsData->removeElement($chartsData);
            // set the owning side to null (unless already changed)
            if ($chartsData->getChart() === $this) {
                $chartsData->setChart(null);
            }
        }

        return $this;
    }

    public function getChartsDataFormatted()
    {
        $chartsData = $this->chartsData;
        $array = [];

        foreach ( $chartsData as $cd ) {
            $array[] = $cd->getData();
        }

        return json_encode($array);
    }

    public function getChartsTitleFormatted()
    {
        $chartsData = $this->chartsData;
        $array = [];

        foreach ( $chartsData as $cd ) {
            $array[] = $cd->getTitle();
        }

        return json_encode($array);
    }

}

templates/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin DashBoard{% endblock %}

{% block body %}

<main>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Admin</h1>
            </div>
        </div>
    </div>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="mb-5">Projects</h2>
                    <div class="row">
                        <div class="col-12">
                            <a href="{{ path('project_update', {'projectID': 'new' }) }}" class="btn btn-primary mb-5">Ajouter</a>
                        </div>
                    </div>
                    <div class="row">
                        {% for project in projects %}
                            <div class="col-md-4">
                                <div class="card">
                                    <img src="{{ project.img }}" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ project.title }}</h5>
                                        <p class="card-text">{{ project.description }}</p>
                                        <a href="{{ path('project_update', {'projectID': project.id }) }}" class="btn btn-primary">Editer</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="mb-5">Graphiques</h2>
                    <div class="row">
                        <div class="col-12">
                            <a href="{{ path('chart_update', {'chartID': 'new' }) }}" class="btn btn-primary mb-5">Ajouter</a>
                        </div>
                    </div>
                    <div class="row">
                        {% for chart in charts %}
                            <div class="col-4">
                                <canvas id="chart-{{ chart.id }}" width="400" height="400"></canvas>
                                <a href="{{ path('chart_update', {'chartID': chart.id }) }}" class="btn btn-primary">Editer</a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="mb-5">Liens</h2>
                    <div class="row">
                        <div class="col-12">
                            <a href="{{ path('link_update', {'linkID': 'new' }) }}" class="btn btn-primary mb-5">Ajouter</a>
                        </div>
                    </div>
                    <div class="row">
                        {% for link in links %}
                            <div class="col-12">
                                <h3><a href="{{ link.url }}">{{ link.title }} </a> <a class="btn btn-primary" href="{{ path('link_update', {'linkID': link.id }) }}"><span>Editer</span></a></h3>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script>
        var randomScalingFactor = function() {
            return Math.round(Math.random() * 255);
        };

        {% for chart in charts %}

        var ctx{{ chart.id }} = document.getElementById('chart-{{ chart.id }}').getContext('2d');

        let data{{ chart.id }} = {{ chart.chartsDataFormatted|raw }};
        let bgColors{{ chart.id }} = [];

        for ( d in data{{ chart.id }} ) {
            let r = randomScalingFactor();
            let g = randomScalingFactor();
            let b = randomScalingFactor();

            bgColors{{ chart.id }}.push(`rgba(${r}, ${g}, ${b}, 1)`);
        }

        var Chart{{ chart.id }} = new Chart(ctx{{ chart.id }}, {
            type: '{{ chart.type }}',
            data: {
                labels: {{ chart.chartsTitleFormatted|raw }},
                datasets: [{
                    label: '{{ chart.title }}',
                    data: data{{ chart.id }},
                    backgroundColor: bgColors{{ chart.id }},
                    borderWidth: 1
                }]
            },
            options: {
                title: {
                    display: true,
                    text: '{{ chart.title }}'
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        {% endfor %}
    </script>
{% endblock %}



templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
            <link rel="stylesheet" href="/css/owl.carousel.min.css">
            <link rel="stylesheet" href="/css/owl.theme.default.min.css">
            <link rel="stylesheet" href="/css/Chart.min.css">
            <link rel="stylesheet" href="/css/style.css">
        {% endblock %}
    </head>
    <body>
    <div id="template-notification">
        <div class="container-fluid">
            {% for type, flash_messages in app.session.flashBag.all %}
                {% for flash_message in flash_messages %}
                    <div role="alert" class="alert alert-{{ type }} alert-icon alert-dismissible">
                        <div class="icon"><span class="s7-check"></span></div>
                        <div class="message">
                            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><i class="fal fa-times"></i></button>{{ flash_message|raw }}
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}

            {% if app.request.hasPreviousSession %}
                {% for type, messages in app.session.flashbag.all() %}
                    {% for message in messages %}
                        <div class="flash-{{ type }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
    </div>

    {% block body %}{% endblock %}
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
            <script src="/js/owl.carousel.min.js"></script>
            <script src="/js/Chart.min.js"></script>
        {% endblock %}
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('admin') }}">Login</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section id="head-home">
        <div class="owl-carousel owl-theme">
            <div class="item"><img src="/img/christian-joudrey-9bdt03k4ujw-unsplash.jpg" alt=""></div>
            <div class="item"><img src="/img/sebastian-pichler-0Ebrm0d-G_E-unsplash.jpg" alt=""></div>
            <div class="item"><img src="/img/christopher-gower-m_HRfLhgABo-unsplash.jpg" alt=""></div>
        </div>
    </section>

    <main>
        <section id="presentation">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2 class="mb-4">Presentation</h2>
                        <p>Bonjour je m'appelle Robin LY UONG. Je suis étudiant en Mastere Expert Développement Web à Ynov Lyon.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend lobortis purus, et pharetra nunc lobortis in. Vivamus ultrices dignissim faucibus. Maecenas sodales nibh at consequat iaculis. Fusce at massa ornare, vehicula mi finibus, condimentum dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                    </div>
                </div>
            </div>
        </section>

        <section id="skills">
            <div class="container">
                <div class="col-12 text-center">
                    <h2 class="mb-4">Graphiques</h2>
                    <p>Simple yet flexible JavaScript charting for designers & developers</p>
                </div>
                <div class="row">
                    {% for chart in charts %}
                        <div class="col-4">
                            <canvas id="chart-{{ chart.id }}" width="400" height="400"></canvas>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>

        <section id="projects">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2 class="mb-4">Projets</h2>
                    </div>
                </div>
                <div class="row">
                    {% for project in projects %}
                        <div class="col-md-4">
                            <div class="card">
                                <img src="{{ project.img }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{ project.title }}</h5>
                                    <p class="card-text">{{ project.description }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>

    <footer class="page-footer font-small blue pt-4">

        <!-- Footer Links -->
        <div class="container text-center text-md-left">

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-md-6 mt-md-0 mt-3">

                    <!-- Content -->
                    <h5 class="text-uppercase">Coordonnés</h5>
                    <p>robin.lyuong@ynov.com</p>
                    <p>0612345678</p>
                    <p></p>
                </div>
                <!-- Grid column -->

                <hr class="clearfix w-100 d-md-none pb-3">

                {% if links %}
                    <div class="col-md-3 mb-md-0 mb-3">

                        <!-- Links -->
                        <h5 class="text-uppercase">Liens</h5>

                        <ul class="list-unstyled">
                            {% for link in links %}
                                <li>
                                    <a class="text-white" href="{{ link.url }}">{{ link.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}



            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2020 Copyright Robin
        </div>
        <!-- Copyright -->

    </footer>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $('.owl-carousel').owlCarousel({
            loop:true,
            autoplay: true,
            items:1,
            dots: false
        });

        var randomScalingFactor = function() {
            return Math.round(Math.random() * 255);
        };

        {% for chart in charts %}

        var ctx{{ chart.id }} = document.getElementById('chart-{{ chart.id }}').getContext('2d');

        let data{{ chart.id }} = {{ chart.chartsDataFormatted|raw }};
        let bgColors{{ chart.id }} = [];

        for ( d in data{{ chart.id }} ) {
            let r = randomScalingFactor();
            let g = randomScalingFactor();
            let b = randomScalingFactor();

            bgColors{{ chart.id }}.push(`rgba(${r}, ${g}, ${b}, 1)`);
        }

        var Chart{{ chart.id }} = new Chart(ctx{{ chart.id }}, {
            type: '{{ chart.type }}',
            data: {
                labels: {{ chart.chartsTitleFormatted|raw }},
                datasets: [{
                    label: '{{ chart.title }}',
                    data: data{{ chart.id }},
                    backgroundColor: bgColors{{ chart.id }},
                    borderWidth: 1
                }]
            },
            options: {
                title: {
                    display: true,
                    text: '{{ chart.title }}'
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        {% endfor %}

    </script>
{% endblock %}



templates/updateChart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Graphique{% endblock %}

{% block body %}

    <main>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>{{ typeForm }} graphique</h1>
                    <a class="btn btn-success" href="/admin">Retour</a>
                </div>
            </div>
        </div>

        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        {% if typeForm == "Modifier" %}
                            {{ form_start(form, { 'action': path('chart_update', {'chartID': chart.id }) }) }}
                        {% else %}
                            {{ form_start(form, { 'action': path('chart_update', {'chartID': 'new' }) }) }}
                        {% endif %}
                        <div class="form-group">
                            {{ form_label(form.title) }}
                            {{ form_widget(form.title) }}
                            <div class="help-block with-errors"></div>
                        </div>

                        <div class="form-group">
                            {{ form_label(form.type) }}
                            {{ form_widget(form.type) }}
                            <div class="help-block with-errors"></div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>

                {% if typeForm == 'Ajouter' %}
                    <div class="row">
                        <div class="col-12 mt-5">
                            <p>Vous pourrez ajouter des données une fois le graphique créé.</p>
                        </div>
                    </div>
                {% endif %}

            </div>
        </section>

        {% if typeForm == "Modifier" %}
            <section>
                <div class="container">
                    <h2>Ajouter une donnée au graphique</h2>
                    <div class="row">
                        <div class="col-md-4">
                            {{ form_start(formChartData, { 'action': path('chart_add_data', {chartID: chart.id }) }) }}

                            <div class="form-group">
                                {{ form_label(formChartData.title, 'Titre') }}
                                {{ form_widget(formChartData.title) }}
                                <div class="help-block with-errors"></div>
                            </div>

                            <div class="form-group">
                                {{ form_label(formChartData.data, 'Valeur') }}
                                {{ form_widget(formChartData.data) }}
                                <div class="help-block with-errors"></div>
                            </div>

                            {{ form_end(formChartData) }}

                        </div>
                    </div>
                </div>
            </section>

            {% if chartsData|length > 0 %}
                <section>
                    <div class="container">
                        <h2>Liste des données</h2>
                        <div class="row">
                            <div class="col-12">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">Titre</th>
                                        <th scope="col">Valeur</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for data in chartsData %}
                                        <form id="chart-data-{{ data.id }}" action="{{ path('chart_update_data', {chartID: chart.id, dataID: data.id }) }}" method="post">
                                            <tr>
                                                <td><input type="text" name="title" value="{{ data.title }}"></td>
                                                <td><input type="text" name="value" value="{{ data.data }}"></td>
                                                <td>
                                                    <input class="btn btn-primary" type="submit" form="chart-data-{{ data.id }}" value="Enregistrer">
                                                    <a class="btn btn-danger" href="{{ path('chart_delete_data', {chartID: chart.id, dataID: data.id }) }}">Supprimer</a>
                                                </td>
                                            </tr>
                                        </form>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            {% endif %}

        {% endif %}

    </main>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/updateLink.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lien{% endblock %}

{% block body %}

    <main>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>{{ typeForm }} un Lien</h1>
                    <a class="btn btn-success" href="/admin">Retour</a>
                </div>
            </div>
        </div>

        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        {% if typeForm == "Modifier" %}
                            {{ form_start(form, { 'action': path('link_update', {'linkID': link.id }) }) }}
                        {% else %}
                            {{ form_start(form, { 'action': path('link_update', {'linkID': 'new' }) }) }}
                        {% endif %}
                        <div class="form-group">
                            {{ form_label(form.title) }}
                            {{ form_widget(form.title) }}
                            <div class="help-block with-errors"></div>
                        </div>

                        <div class="form-group">
                            {{ form_label(form.url) }}
                            {{ form_widget(form.url) }}
                            <div class="help-block with-errors"></div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}



templates/updateProject.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projet!{% endblock %}

{% block body %}

    <main>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>{{ typeForm }} un Projet</h1>
                    <a class="btn btn-success" href="/admin">Retour</a>
                </div>
            </div>
        </div>

        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        {% if typeForm == "Modifier" %}
                            {{ form_start(form, { 'action': path('project_update', {'projectID': project.id }) }) }}
                        {% else %}
                            {{ form_start(form, { 'action': path('project_update', {'projectID': 'new' }) }) }}
                        {% endif %}
                        <div class="form-group">
                            {{ form_label(form.title) }}
                            {{ form_widget(form.title) }}
                            <div class="help-block with-errors"></div>
                        </div>

                        <div class="form-group">
                            {{ form_label(form.description) }}
                            {{ form_widget(form.description) }}
                            <div class="help-block with-errors"></div>
                        </div>

                        <div class="form-group">
                            {{ form_label(form.img) }}
                            {{ form_widget(form.img) }}
                            <div class="help-block with-errors"></div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

